// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4keHwAf5uUfHS4m7QKbcQt5hySpJjri0',
    appId: '1:179049673161:web:2607fca7e348aa2189b818',
    messagingSenderId: '179049673161',
    projectId: 'fit-movies-flutter-app',
    authDomain: 'fit-movies-flutter-app.firebaseapp.com',
    storageBucket: 'fit-movies-flutter-app.firebasestorage.app',
    measurementId: 'G-XM6PTX5661',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQZWStbgoPxoG-3ZLApn6lq-b86dqEDhM',
    appId: '1:179049673161:android:636fe6f2f26eac8a89b818',
    messagingSenderId: '179049673161',
    projectId: 'fit-movies-flutter-app',
    storageBucket: 'fit-movies-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC8xgx1AaigUsXgiOdyZYKn7N1cKbc_xI',
    appId: '1:179049673161:ios:cd226fb986f6211389b818',
    messagingSenderId: '179049673161',
    projectId: 'fit-movies-flutter-app',
    storageBucket: 'fit-movies-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.fitMoviesApp',
  );
}
