# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
FIREBASE_APP_ID = ENV["FIREBASE_APP_ID"]
FIREBASE_TOKEN = ENV["FIREBASE_TOKEN"]

default_platform(:android)

platform :android do

  # Run tests
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # Build apk
  desc "Builds the APK"
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end

  # Upload to firebase
  desc "Uploads to Firebase App Distribution"
  lane :build_firebase do
    firebase_app_distribution(
      app: "#{FIREBASE_APP_ID}",
      firebase_cli_token: "#{FIREBASE_TOKEN}",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      groups: "Internal Tester",
      release_notes: "Lots of amazing new features to test out!"
    )
  end

end
